/**
 * ---------------------------------------
 * This demo was created using amCharts 4.
 *
 * For more information visit:
 * https://www.amcharts.com/
 *
 * Documentation is available at:
 * https://www.amcharts.com/docs/v4/
 * ---------------------------------------
 */

am4core.useTheme(am4themes_animated);

var chart = am4core.create("chartdiv", am4charts.ChordDiagram);
chart.data = [
  // Define colors
 {"from": "SE_IN_information", "nodeColor": "#2F4A9F" },
{"from": "SE_IN_contestation", "nodeColor": "#4B68B1" },
{"from": "SE_IN_situated approaches", "nodeColor": "#4C7DB1" },
{"from": "SE_IN_extended networks", "nodeColor": "#4E8CB0" },
{"from": "SE_IN_new methodologies", "nodeColor": "#53C6DA" },
{"from": "SE_IN_participation", "nodeColor": "#8FD5E1" },
{"from": "SE_IN_new policies", "nodeColor": "#91D4D3" },
{"from": "SE_IN_volunteering", "nodeColor": "#56C3BC" },
{"from": "SE_IN_system transition", "nodeColor": "#C6F0F8" },
{"from": "SE_IN_external action", "nodeColor": "#2498C5" },
{"from": "SE_IN_local action", "nodeColor": "#12B1D2" },
{"from": "SE_DO_aid", "nodeColor": "#4DBD88" },
{"from": "SE_DO_diversification", "nodeColor": "#61BD5C" },
{"from": "SE_DO_equality", "nodeColor": "#86C54D" },
{"from": "SE_DO_resource access", "nodeColor": "#AFD246" },
{"from": "SE_DO_short-term gains", "nodeColor": "#C8DC4E" },
{"from": "SE_RO_capacity building", "nodeColor": "#935FB2" },
{"from": "SE_RO_empowerment", "nodeColor": "#B775DF" },
{"from": "SE_RO_inclusion", "nodeColor": "#E0ADFF" },
{"from": "SE_PO_accountability", "nodeColor": "#ED1B62" },
{"from": "SE_PO_local interests", "nodeColor": "#ED4F8B" },
{"from": "SE_PO_enhanced processes", "nodeColor": "#DF75AE" },
{"from": "SE_PO_governance capacity", "nodeColor": "#FCB1DA" },
{"from": "SE_TO_new knowledge", "nodeColor": "#96A6B3" },
{"from": "SE_TO_structural change", "nodeColor": "#60717B" },
{"from": "SE_MO_entrepreneurs", "nodeColor": "#FCFF59" },
{"from": "SE_MO_productivity", "nodeColor": "#EEDD24" },
{"from": "SE_CO_mitigation", "nodeColor": "#F37639" },
{"from": "SE_CO_reduced impacts", "nodeColor": "#EA322A" },
{"from": "Other", "nodeColor": "#D9D9D9" },
  
  // Actual data
  { "from": "SE_IN_participation", "to": "Other", "value": 4 },
{ "from": "SE_IN_participation", "to": "SE_CO_mitigation", "value": 1 },
{ "from": "SE_IN_participation", "to": "SE_CO_reduced impacts", "value": 2 },
{ "from": "SE_IN_participation", "to": "SE_DO_aid", "value": 1 },
{ "from": "SE_IN_participation", "to": "SE_DO_diversification", "value": 1 },
{ "from": "SE_IN_participation", "to": "SE_DO_equality", "value": 2 },
{ "from": "SE_IN_participation", "to": "SE_DO_resource access", "value": 2 },
{ "from": "SE_IN_participation", "to": "SE_IN_extended networks", "value": 2 },
{ "from": "SE_IN_participation", "to": "SE_IN_new policies", "value": 1 },
{ "from": "SE_IN_participation", "to": "SE_IN_situated approaches", "value": 1 },
{ "from": "SE_IN_participation", "to": "SE_IN_system transition", "value": 1 },
{ "from": "SE_IN_participation", "to": "SE_MO_productivity", "value": 1 },
{ "from": "SE_IN_participation", "to": "SE_PO_accountability", "value": 1 },
{ "from": "SE_IN_participation", "to": "SE_PO_enhanced processes", "value": 6 },
{ "from": "SE_IN_participation", "to": "SE_RO_capacity building", "value": 2 },
{ "from": "SE_IN_participation", "to": "SE_RO_empowerment", "value": 5 },
{ "from": "SE_IN_participation", "to": "SE_RO_inclusion", "value": 5 },
{ "from": "SE_IN_participation", "to": "SE_TO_new knowledge", "value": 4 },
{ "from": "SE_IN_participation", "to": "SE_TO_structural change", "value": 3 },
{ "from": "SE_IN_contestation", "to": "SE_DO_equality", "value": 1 },
{ "from": "SE_IN_contestation", "to": "SE_IN_extended networks", "value": 3 },
{ "from": "SE_IN_contestation", "to": "SE_IN_local action", "value": 1 },
{ "from": "SE_IN_contestation", "to": "SE_IN_situated approaches", "value": 2 },
{ "from": "SE_IN_contestation", "to": "SE_MO_productivity", "value": 1 },
{ "from": "SE_IN_contestation", "to": "SE_PO_accountability", "value": 1 },
{ "from": "SE_IN_contestation", "to": "SE_PO_enhanced processes", "value": 2 },
{ "from": "SE_IN_contestation", "to": "SE_PO_local interests", "value": 7 },
{ "from": "SE_IN_contestation", "to": "SE_RO_empowerment", "value": 2 },
{ "from": "SE_IN_contestation", "to": "SE_TO_new knowledge", "value": 2 },
{ "from": "SE_IN_contestation", "to": "SE_TO_structural change", "value": 2 },
{ "from": "SE_IN_external action", "to": "SE_CO_reduced impacts", "value": 1 },
{ "from": "SE_IN_external action", "to": "SE_DO_aid", "value": 1 },
{ "from": "SE_IN_external action", "to": "SE_DO_diversification", "value": 1 },
{ "from": "SE_IN_external action", "to": "SE_DO_equality", "value": 2 },
{ "from": "SE_IN_external action", "to": "SE_DO_resource access", "value": 3 },
{ "from": "SE_IN_external action", "to": "SE_IN_extended networks", "value": 2 },
{ "from": "SE_IN_external action", "to": "SE_IN_local action", "value": 3 },
{ "from": "SE_IN_external action", "to": "SE_IN_new policies", "value": 1 },
{ "from": "SE_IN_external action", "to": "SE_IN_participation", "value": 4 },
{ "from": "SE_IN_external action", "to": "SE_IN_situated approaches", "value": 2 },
{ "from": "SE_IN_external action", "to": "SE_PO_enhanced processes", "value": 1 },
{ "from": "SE_IN_external action", "to": "SE_RO_capacity building", "value": 2 },
{ "from": "SE_IN_external action", "to": "SE_RO_empowerment", "value": 2 },
{ "from": "SE_IN_external action", "to": "SE_RO_inclusion", "value": 1 },
{ "from": "SE_IN_external action", "to": "SE_TO_new knowledge", "value": 1 },
{ "from": "SE_IN_external action", "to": "SE_TO_structural change", "value": 1 },
{ "from": "SE_IN_local action", "to": "Other", "value": 1 },
{ "from": "SE_IN_local action", "to": "SE_CO_reduced impacts", "value": 1 },
{ "from": "SE_IN_local action", "to": "SE_DO_diversification", "value": 1 },
{ "from": "SE_IN_local action", "to": "SE_DO_resource access", "value": 1 },
{ "from": "SE_IN_local action", "to": "SE_PO_enhanced processes", "value": 2 },
{ "from": "SE_IN_local action", "to": "SE_PO_governance capacity", "value": 1 },
{ "from": "SE_IN_local action", "to": "SE_PO_local interests", "value": 1 },
{ "from": "SE_IN_local action", "to": "SE_RO_empowerment", "value": 2 },
{ "from": "SE_IN_local action", "to": "SE_TO_new knowledge", "value": 3 },
{ "from": "SE_IN_local action", "to": "SE_TO_structural change", "value": 1 },
{ "from": "SE_IN_extended networks", "to": "SE_DO_diversification", "value": 1 },
{ "from": "SE_IN_extended networks", "to": "SE_DO_resource access", "value": 2 },
{ "from": "SE_IN_extended networks", "to": "SE_IN_local action", "value": 2 },
{ "from": "SE_IN_extended networks", "to": "SE_IN_situated approaches", "value": 1 },
{ "from": "SE_IN_extended networks", "to": "SE_PO_enhanced processes", "value": 1 },
{ "from": "SE_IN_extended networks", "to": "SE_PO_local interests", "value": 2 },
{ "from": "SE_IN_extended networks", "to": "SE_TO_new knowledge", "value": 2 },
{ "from": "SE_IN_situated approaches", "to": "SE_DO_aid", "value": 1 },
{ "from": "SE_IN_situated approaches", "to": "SE_PO_local interests", "value": 1 },
{ "from": "SE_IN_situated approaches", "to": "SE_RO_capacity building", "value": 1 },
{ "from": "SE_IN_situated approaches", "to": "SE_TO_new knowledge", "value": 1 },
{ "from": "SE_IN_information", "to": "SE_CO_reduced impacts", "value": 1 },
{ "from": "SE_IN_information", "to": "SE_DO_diversification", "value": 1 },
{ "from": "SE_IN_information", "to": "SE_DO_resource access", "value": 1 },
{ "from": "SE_IN_information", "to": "SE_IN_external action", "value": 1 },
{ "from": "SE_IN_information", "to": "SE_IN_participation", "value": 2 },
{ "from": "SE_IN_information", "to": "SE_MO_productivity", "value": 1 },
{ "from": "SE_IN_information", "to": "SE_PO_enhanced processes", "value": 1 },
{ "from": "SE_IN_information", "to": "SE_RO_empowerment", "value": 3 },
{ "from": "SE_IN_information", "to": "SE_RO_inclusion", "value": 2 },
{ "from": "SE_IN_information", "to": "SE_TO_new knowledge", "value": 1 },
{ "from": "SE_IN_information", "to": "SE_TO_structural change", "value": 1 },
{ "from": "SE_IN_new methodologies", "to": "SE_CO_reduced impacts", "value": 1 },
{ "from": "SE_IN_new methodologies", "to": "SE_DO_equality", "value": 1 },
{ "from": "SE_IN_new methodologies", "to": "SE_PO_local interests", "value": 1 },
{ "from": "SE_IN_new methodologies", "to": "SE_RO_capacity building", "value": 1 },
{ "from": "SE_IN_new methodologies", "to": "SE_RO_empowerment", "value": 1 },
{ "from": "SE_IN_new methodologies", "to": "SE_TO_new knowledge", "value": 2 },
{ "from": "SE_IN_new policies", "to": "SE_DO_diversification", "value": 1 },
{ "from": "SE_IN_new policies", "to": "SE_IN_extended networks", "value": 1 },
{ "from": "SE_IN_new policies", "to": "SE_IN_local action", "value": 1 },
{ "from": "SE_IN_new policies", "to": "SE_RO_capacity building", "value": 1 },
{ "from": "SE_IN_new policies", "to": "SE_RO_empowerment", "value": 1 },
{ "from": "SE_IN_new policies", "to": "SE_TO_structural change", "value": 1 },
{ "from": "SE_IN_system transition", "to": "Other", "value": 1 },
{ "from": "SE_IN_system transition", "to": "SE_CO_mitigation", "value": 1 },
{ "from": "SE_IN_system transition", "to": "SE_DO_equality", "value": 2 },
{ "from": "SE_IN_system transition", "to": "SE_MO_productivity", "value": 1 },
{ "from": "SE_IN_system transition", "to": "SE_TO_structural change", "value": 1 },
{ "from": "SE_IN_volunteering", "to": "SE_DO_equality", "value": 1 },
{ "from": "SE_IN_volunteering", "to": "SE_DO_resource access", "value": 1 },
{ "from": "SE_IN_volunteering", "to": "SE_IN_information", "value": 1 },
{ "from": "SE_IN_volunteering", "to": "SE_IN_participation", "value": 1 },
{ "from": "SE_IN_volunteering", "to": "SE_RO_empowerment", "value": 2 },
{ "from": "SE_IN_volunteering", "to": "SE_RO_inclusion", "value": 1 },
{ "from": "Other", "to": "SE_CO_reduced impacts", "value": 3 },
{ "from": "Other", "to": "SE_DO_equality", "value": 1 },
{ "from": "Other", "to": "SE_DO_resource access", "value": 3 },
{ "from": "Other", "to": "SE_DO_short-term gains", "value": 1 },
{ "from": "Other", "to": "SE_PO_governance capacity", "value": 4 },
{ "from": "Other", "to": "SE_PO_local interests", "value": 1 },
{ "from": "Other", "to": "SE_RO_empowerment", "value": 3 },
{ "from": "Other", "to": "SE_TO_new knowledge", "value": 1 },
{ "from": "Other", "to": "SE_TO_structural change", "value": 3 },
{ "from": "SE_CO_mitigation", "to": "SE_DO_equality", "value": 1 },
{ "from": "SE_CO_mitigation", "to": "SE_DO_resource access", "value": 1 },
{ "from": "SE_CO_mitigation", "to": "SE_TO_structural change", "value": 1 },
{ "from": "SE_CO_reduced impacts", "to": "SE_RO_capacity building", "value": 1 },
{ "from": "SE_CO_reduced impacts", "to": "SE_RO_inclusion", "value": 1 },
{ "from": "SE_CO_reduced impacts", "to": "SE_TO_new knowledge", "value": 3 },
{ "from": "SE_DO_aid", "to": "SE_RO_capacity building", "value": 1 },
{ "from": "SE_DO_diversification", "to": "SE_CO_reduced impacts", "value": 1 },
{ "from": "SE_DO_diversification", "to": "SE_DO_resource access", "value": 2 },
{ "from": "SE_DO_diversification", "to": "SE_DO_short-term gains", "value": 1 },
{ "from": "SE_DO_diversification", "to": "SE_RO_capacity building", "value": 1 },
{ "from": "SE_DO_diversification", "to": "SE_RO_empowerment", "value": 2 },
{ "from": "SE_DO_diversification", "to": "SE_RO_inclusion", "value": 1 },
{ "from": "SE_DO_diversification", "to": "SE_TO_new knowledge", "value": 1 },
{ "from": "SE_DO_diversification", "to": "SE_TO_structural change", "value": 2 },
{ "from": "SE_DO_resource access", "to": "SE_CO_reduced impacts", "value": 2 },
{ "from": "SE_DO_resource access", "to": "SE_DO_equality", "value": 1 },
{ "from": "SE_DO_resource access", "to": "SE_RO_empowerment", "value": 4 },
{ "from": "SE_DO_resource access", "to": "SE_RO_inclusion", "value": 1 },
{ "from": "SE_DO_resource access", "to": "SE_TO_new knowledge", "value": 1 },
{ "from": "SE_DO_resource access", "to": "SE_TO_structural change", "value": 1 },
{ "from": "SE_MO_entrepreneurs", "to": "Other", "value": 1 },
{ "from": "SE_MO_entrepreneurs", "to": "SE_CO_reduced impacts", "value": 1 },
{ "from": "SE_MO_entrepreneurs", "to": "SE_MO_productivity", "value": 2 },
{ "from": "SE_MO_productivity", "to": "Other", "value": 3 },
{ "from": "SE_MO_productivity", "to": "SE_CO_reduced impacts", "value": 2 },
{ "from": "SE_MO_productivity", "to": "SE_DO_diversification", "value": 1 },
{ "from": "SE_MO_productivity", "to": "SE_DO_equality", "value": 1 },
{ "from": "SE_MO_productivity", "to": "SE_DO_resource access", "value": 2 },
{ "from": "SE_MO_productivity", "to": "SE_PO_local interests", "value": 1 },
{ "from": "SE_MO_productivity", "to": "SE_RO_empowerment", "value": 1 },
{ "from": "SE_MO_productivity", "to": "SE_RO_inclusion", "value": 1 },
{ "from": "SE_MO_productivity", "to": "SE_TO_new knowledge", "value": 2 },
{ "from": "SE_MO_productivity", "to": "SE_TO_structural change", "value": 1 },
{ "from": "SE_PO_enhanced processes", "to": "Other", "value": 4 },
{ "from": "SE_PO_enhanced processes", "to": "SE_CO_reduced impacts", "value": 2 },
{ "from": "SE_PO_enhanced processes", "to": "SE_PO_governance capacity", "value": 4 },
{ "from": "SE_PO_enhanced processes", "to": "SE_PO_local interests", "value": 1 },
{ "from": "SE_PO_enhanced processes", "to": "SE_RO_empowerment", "value": 2 },
{ "from": "SE_PO_enhanced processes", "to": "SE_RO_inclusion", "value": 1 },
{ "from": "SE_PO_enhanced processes", "to": "SE_TO_new knowledge", "value": 4 },
{ "from": "SE_PO_enhanced processes", "to": "SE_TO_structural change", "value": 2 },
{ "from": "SE_PO_local interests", "to": "SE_RO_capacity building", "value": 1 },
{ "from": "SE_RO_empowerment", "to": "SE_CO_reduced impacts", "value": 2 },
{ "from": "SE_RO_empowerment", "to": "SE_DO_equality", "value": 1 },
{ "from": "SE_RO_empowerment", "to": "SE_PO_accountability", "value": 1 },
{ "from": "SE_RO_empowerment", "to": "SE_PO_local interests", "value": 1 },
{ "from": "SE_RO_empowerment", "to": "SE_RO_capacity building", "value": 3 },
{ "from": "SE_RO_empowerment", "to": "SE_RO_inclusion", "value": 5 },
{ "from": "SE_RO_empowerment", "to": "SE_TO_new knowledge", "value": 1 },
{ "from": "SE_RO_empowerment", "to": "SE_TO_structural change", "value": 3 },
{ "from": "SE_RO_inclusion", "to": "SE_RO_capacity building", "value": 1 },
{ "from": "SE_TO_new knowledge", "to": "SE_RO_inclusion", "value": 2 },
{ "from": "SE_TO_structural change", "to": "SE_CO_reduced impacts", "value": 1 },
{ "from": "SE_TO_structural change", "to": "SE_DO_equality", "value": 1 },
{ "from": "SE_TO_structural change", "to": "SE_PO_governance capacity", "value": 3 },
{ "from": "SE_TO_structural change", "to": "SE_RO_capacity building", "value": 1 },
{ "from": "SE_TO_structural change", "to": "SE_RO_inclusion", "value": 2 },
{ "from": "SE_TO_structural change", "to": "SE_TO_new knowledge", "value": 1 }
];

chart.dataFields.fromName = "from";
chart.dataFields.toName = "to";
chart.dataFields.value = "value";
chart.dataFields.color = "nodeColor";

// Configure ribbon appearance
var slice = chart.nodes.template.slice;

// Configure links
var link = chart.links.template;
link.fillOpacity = 0.8;

// Configure labels
var label = chart.nodes.template.label;
label.fontSize = 12;
label.fill = am4core.color("#555");

// Enable export
chart.exporting.menu = new am4core.ExportMenu();